apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bot.service.name }}
  labels:
    {{- include "rosco-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.bot.service.type }}
  ports:
    # headless service, define port to not make the kubernetes gods angry
    - port: 1234
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ .Values.bot.service.name }}