apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.api.service.name }} 
  annotations:
    keel.sh/policy: {{ .Values.keel.globPattern }}
    keel.sh/pollSchedule: "@every 30s"
  labels:
    {{- include "rosco-helm.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "rosco-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rosco-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rosco-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Values.api.secretName }}
          env:
            {{- toYaml .Values.bot.env | nindent 10 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          volumeMounts:
            - name: postgres-cert
              mountPath: /etc/rosco/ca-certificate.crt
              subPath: ca-certificate.crt
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
          - name: postgres-cert
            configMap:
              name: postgres-cert
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
