apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.service.name }} 
  labels:
    {{- include "rosco-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "rosco-helm.selectorLabels" . | nindent 4 }}