replicacount: 2

postgresql:
  enabled: true
  persistence:
    enabled: true

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts: 
    - host: wiki.roscobot.com
      paths:
        - path: /?(.*)
          pathType: Prefix
    - host: www.wiki.roscobot.com
      paths:
        - path: /?(.*)
          pathType: Prefix
  tls:
    - hosts:
        - www.wiki.roscobot.com
        - wiki.roscobot.com
      secretName: tls-secret-roscobot-wiki