version: '3'
services:
  bot:
    image: docker.io/ryanpage/guac-bot:latest
    network_mode: host
    env_file:
      - ./.env
  db:
    image: postgres:latest
    container_name: guac-bot-db
    ports: 
    - 5433:5432
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_USER: guac-bot
      POSTGRES_DB: guac_bot_db 
  redis:
    image: redis:latest
    container_name: guac-bot-redis
    ports:
      - 6379:6379
