const Colors = {
    ANCHOR_LIGHT: '#1c76fe',
    BACKGROUND_DARK: '#535353',
    BACKGROUND_DARKER: '#252525',
    BACKGROUND_LIGHT: '#FFFFFF',
    BACKGROUND_MEDIUM: '#3f3f3f',
    BUTTON_INVITE_HOVER: '#bef0ff',
    BUTTON_INVITE: '#A3DCEE',
    DROPDOWN_BACKGROUND_LIGHT: '#f0f0f0',
    TEXT_DARK: '#000000',
    TEXT_LIGHT_HOVER: '#c4c4c4',
    TEXT_LIGHT: '#FFFFFF',
    TEXT_MEDIUM: '#b5b5b5'
};

export default Colors;