name: After Release

on:
  release:
    types: [published]

jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: POST to webhook
      working-directory: ./bot
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      run: |
        npm i -g yarn
        yarn install
        echo "NOTES='$(npx ts-node docs/getFirstSection.ts)EOF'" >> $GITHUB_ENV
        echo $NOTES
        curl \
          -H "Content-Type: application/json" \
          -d '{ "username": "Rosco Updates", "content": "${{ env.NOTES }}"}' \
          $DISCORD_WEBHOOK