name: After Release

on:
  release:
    types: [published]

jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Name: ${{ github.event.release.name }} Description: ${{ github.event.release.body }}"
      - name: POST to webhook
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d '{ "username": "Rosco Updates", "content": "${{ github.event.release.body }}"}' \
            $DISCORD_WEBHOOK