name: Build & Run Tests

on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: build bot
        run: |
          yarn install
          npx tsc
        working-directory: ./bot
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_guacbot_db
          POSTGRES_PASSWORD: adminadmin
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: build bot
        run: |
          yarn install
          yarn jest
        working-directory: ./bot