name: Build and Deploy Docker Images

on:
  workflow_run:
    workflows: ['Build & Run Tests']
    branches: ['*']
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: build bot
        run: |
          yarn install
          npx tsc
          export PUSH=true; ./buildDocker.sh ryanpage/guac-bot latest
          export PUSH=true; ./buildDocker.sh ryanpage/guac-bot ${{ github.run_number }}
        working-directory: ./bot
      